repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3 # Use a versão do ruff que você instalou
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
